### ISSUE TITLE
[Epic] Developer UX Sprint 5

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#1015]
- [ ] #1031
- [ ] #1068 
- [ ] #1017 
- [ ]     - Public archive nodes w/ API keys / rate limiting
- [ ]     - Documentation for the code itself & improved abstractions
- [ ] Reach out to Frojdi to ask about dynamic protobuf loading from a full node & how it would work for a typescript
  - @Dev make an intro over discord
- [x] Linting work
- [x] - fixing bugs for installer from genesis

TODO: Maybe break down into segments, so we can track whats relevant to each thing
