### ISSUE TITLE
[Epic] Database layer performance and stability

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1016]
**Completed**
- [x] IAVL state export --height bug
  - Appears to have fixed the app hash mismatch being observed
- [x] #1037
- [x] Backport 7.0.3 IAVL changes to v6.4.0
- [x] #1042
- [x] https://github.com/osmosis-labs/iavl/issues/22
- [x] #1065
- [x] https://github.com/osmosis-labs/osmosis/issues/932
- [x] https://github.com/osmosis-labs/osmosis/issues/1137
- [x] https://github.com/osmosis-labs/cosmos-sdk/pull/155
- [x] https://github.com/osmosis-labs/iavl/issues/24
- [x] #1041
- [x] #1175
- [x] https://github.com/osmosis-labs/cosmos-sdk/issues/149

**In progress**
- [ ] https://github.com/osmosis-labs/osmosis/issues/1140

- [ ] https://github.com/osmosis-labs/osmosis/issues/1163

**Medium Priority**

- [ ] https://github.com/osmosis-labs/cosmos-sdk/issues/148

**Blocked**
- [ ] #1090
  - Planning to not spend too much time on investigating on nodes, until we get an improved mainnet node setup automation, via ansible & prometheus. Otherwise we spend all the time in node setup / attempts at reproducing
  - We also want to try reproducing in the e2e test suite once its further along

**Comment by p0mvn** [comment]
As discussed in sprint planning, this epic is getting closed. #1163 and https://github.com/osmosis-labs/cosmos-sdk/issues/148 are getting moved as frogs to the current sprint while all the remaining issues are moved to be tracked #1172 without specific priority assigned to them
