### ISSUE TITLE
[Epic] Token Factory Module

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1029]
The token factory module is a module that will enable new native tokens to be minted on Osmosis, with well prefixed names. This is important for cosmwasm applications on osmosis to thrive.

- [x] #584 
  - Get initial PR merged 
- [x] Disable force transfer code
- [x] #689 
- [x] Add friction (base osmo fee) to token factory token creation #1435
- [x] Code spec
- [ ] Test usage in cosmwasm contract / provide example contract making use of this

**Comment by sunnya97** [comment]
We should add checks that prevent force transferring or burning from module accounts.

**Comment by sunnya97** [comment]
Let's go ahead and reduce the scope such that minting and burning can only happen in the triggering account.

**Comment by p0mvn** [comment]
I'm cleaning up the epics and seeing some checkboxes without issues. @sunnya97 @ValarDragon could you update the epic to cross out the completed items and create issues for items that still need work. Thank you!

**Comment by mattverse** [comment]
Closing this issue to replace with issues with more details and specifics
