### ISSUE TITLE
[Epic] Superfluid Sprint 5

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1030]
Superfluid changes we want to land soon:

- [x] osmosis-labs/osmosis#1032
  - We believe that the code should work, but want to be pragmatic on testing this before it gets deployed on mainnet
- [x] osmosis-labs/osmosis#1018 
- [x] osmosis-labs/osmosis#1033
  - Re-usable methods using begin block, msg's, and other suite's messages
  - See #
- [ ] Deposit spam fixes
  -  https://github.com/osmosis-labs/cosmos-sdk/issues/112
  -  https://github.com/osmosis-labs/cosmos-sdk/issues/113
  - Need to make it on a v8 version
- [x] osmosis-labs/osmosis#1072
- [x] osmosis-labs/osmosis#1059 
- [x] Genesis fixes (link Eugen's 2 PRs)
- [ ] osmosis-labs/osmosis#1083 
- [ ] osmosis-labs/osmosis#1120
- [ ] Test the invariant on mainnet
  - Make a new v7 branch that enables the new invariant, and comments out the GAMM invariant
  - Take a node that is synced, switch to this new branch
  - Restart node with the flag for `invariant-interval` (flag is `--inv-check-period`)
  - Off by rounding error, want to make a sum of locks vs accumulation store invariant. Needs issue

**Comment by czarcas7ic** [comment]
Added superfluid params.

Am I right is saying @p0mvn fixed the import/export issue already?

**Comment by p0mvn** [comment]
I believe so, unless there is another issue that I don't know of

**Comment by ValarDragon** [comment]
I don't think we've ever tested import <> export correctness for superfluid. E.g. Eugen found a bug during his simulation work last week

**Comment by daniel-farina** [comment]
I moved docs to #30

- [ ] osmosis-labs/docs#53
- [ ] osmosis-labs/osmosis#1073
