### ISSUE TITLE
[Epic] Integrate Agoric's clawbacked vesting module

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1092]
Talked to Jim, he was extremely helpful explaining the code in the Agoric codebase! Also talked with Matt about it, and we wrote this doc together explaining the feature:

# Vesting with Clawback

On-chain vesting with clawback is a very nice feature to have for teams to use as vesting structures for agreements on-chain. A common equity structuring is "4 year vesting, with 1 year cliff", meaning that for the first year, under some {conditions}, all equity could go back to the issuer. (e.g. if the person left the team)

A requested feature on Osmosis is being able to do this clawback feature, where someone can have an address thats getting tokens under some cliffed + linear unlock vesting schedule, but have an entity who can clawback all unvested tokens.

## Implementation History

Agoric has implemented a lot of this work (plus more) in their repo here: https://github.com/agoric-labs/cosmos-sdk

However they implement a much more complex case, e.g. allowing staking of unvested tokens, and their use case of liens.

In our case, we'd like to have staking of unvested tokens be blocked. Evmos is said to have copied the Agoric code into their own vesting module here: https://github.com/tharsis/evmos/tree/main/x/vesting , and paired it down to implement precisely this usecase.

## Suggested Plan

- [ ] Audit the Evmos code, and see if it does implement a clawback address for unvested tokens. If so, does this vesting have a cliff lock + linear vest?
- [ ] Copy / paste into Osmosis, figure out if theres any integration needed into auth module. (Check Evmos code to see if they do any)
    - [ ] Its a real possibility that the code may be under-tested. We should think of tests we'd expect / want, and write them in our fork.
- [ ] Check in with Agoric code (Or can ask jim larson), to see if our proto structs are very different from theres, and/or is there a clean upgrade path available. 
    - [ ] Check how https://github.com/agoric-labs/cosmos-sdk/blob/Agoric/proto/cosmos/vesting/v1beta1/vesting.proto#L95 and https://github.com/tharsis/evmos/blob/main/proto/evmos/vesting/v1/vesting.proto compare
    - [ ] Consider if we should change the proto routes to be what will be in the SDK.
    - [ ] Evmos does odd things with their encoding config, we need to double check it works for us
- [ ] Make plan for testing on testnet

**Comment by ValarDragon** [comment]
Talked to Jim, he was extremely helpful explaining the code in the Agoric codebase! Also talked with Matt about it, and we wrote this doc together explaining the feature:

# Vesting with Clawback

On-chain vesting with clawback is a very nice feature to have for teams to use as vesting structures for agreements on-chain. A common equity structuring is "4 year vesting, with 1 year cliff", meaning that for the first year, under some {conditions}, all equity could go back to the issuer. (e.g. if the person left the team)

A requested feature on Osmosis is being able to do this clawback feature, where someone can have an address thats getting tokens under some cliffed + linear unlock vesting schedule, but have an entity who can clawback all unvested tokens.

## Implementation History

Agoric has implemented a lot of this work (plus more) in their repo here: https://github.com/agoric-labs/cosmos-sdk

However they implement a much more complex case, e.g. allowing staking of unvested tokens, and their use case of liens.

In our case, we'd like to have staking of unvested tokens be blocked. Evmos is said to have copied the Agoric code into their own vesting module here: https://github.com/tharsis/evmos/tree/main/x/vesting , and paired it down to implement precisely this usecase.

## Suggested Plan

- [ ] Audit the Evmos code, and see if it does implement a clawback address for unvested tokens. If so, does this vesting have a cliff lock + linear vest?
- [ ] Copy / paste into Osmosis, figure out if theres any integration needed into auth module. (Check Evmos code to see if they do any)
    - [ ] Its a real possibility that the code may be under-tested. We should think of tests we'd expect / want, and write them in our fork.
- [ ] Check in with Agoric code (Or can ask jim larson), to see if our proto structs are very different from theres, and/or is there a clean upgrade path available. 
    - [ ] Check how https://github.com/agoric-labs/cosmos-sdk/blob/Agoric/proto/cosmos/vesting/v1beta1/vesting.proto#L95 and https://github.com/tharsis/evmos/blob/main/proto/evmos/vesting/v1/vesting.proto compare
    - [ ] Consider if we should change the proto routes to be what will be in the SDK.
    - [ ] Evmos does odd things with their encoding config, we need to double check it works for us
- [ ] Make plan for testing on testnet

**Comment by ValarDragon** [comment]
Woah totally forgot! That'd be awesome!

Whats the best way for us to do this? Should we open a PR or branch for the entire module against this repo, and then review / PR changes against that branch?

**Comment by alexanderbez** [comment]
Yeah, I say we:

1. Quickly review what Evmos has
2. Quickly review what Agoric has and that the Evmos version has what we need and nothing else
3. Import/copy the module and review more fully

**Comment by mattverse** [comment]
I've briefly went over Agoric & Evmos' implementation of the clawback and as @ValarDragon mentioned, Agoric's implementation does have more complexity, as it can stake the vested tokens: The clawback logic has higher complexity as well since clawing back would include the procedure of ( clawback from account -> check delegations and clawback -> check undelegations clawback). 


Also, Evmos's implementation does support cliff + linear vest: making it possible to implement clawback mainly based on Evmos' implementation. The implementation for Evmos tho, is not purely based on sdk, implemented more like a module, so my take would be switching in between agoric's and Evmos' implmenetations!

**Comment by alexanderbez** [comment]
Sounds good @mattverse! I presume you're referring to the [`x/vesting`](https://github.com/tharsis/evmos/tree/main/x) module of Evmos? We have two options really:

1. Import the module directly
2. Copy/fork the module

(1) is the ideal and cleaner option assuming we've fully vetted and reviewed it. But also has the downside of being locked into whatever SDK version that Evmos is using.

(2) Requires slightly more work and also requires a maintenance burden, but on the flip side it offers greater flexibility since we "own" it.
