### ISSUE TITLE
[Epic] Routing module

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1099]
Theres a growing number of use cases that want to be able to route actions on Osmosis. Cosmwasm apps are going to likely want to just trade between denoms, and abstract out the details of what pool IDs are underneath. One step better is if they can just use the 'real' asset names instead of the IBC hashes, further abstracting out IBC channel details from them.

Bech32-ibc routing similarly wants to track the IBC denom data for each field. Txfees wants to know an osmo pool for every module.

I suggest we build a routing module to enable these use cases. The module should contain a table of:
```
asset_name | ibc channel | ibc denom (on Osmosis) | incentivized pool IDs | osmo incentivized pool ID
```

Not all fields need to be filled in. (e.g. incentivized pool ID, osmo incentivized pool ID, ibc channel can be blank)
An example fill in would be `uregen | channel-8 | ibc/1DCC8A6CB5689018431323953344A9F6CC4D0BFB261E88C9F7777372C10CD076 | 22,42,548 | 42`

An initial implementation of this ideally would use the ORM module (https://github.com/cosmos/cosmos-sdk/tree/master/orm) , checkout regen's modules to see how its used. We should check out regen's eco credit module for how ORM is used: https://github.com/regen-network/regen-ledger/tree/master/x/ecocredit

Steps for this epic, ideally each would be its own PR:

```[tasklist]
### Routing module Tasks
- [ ] Initial implementation of a routing module's table in state, using ORM
- [ ] Add hook to incentivized pool proposals, to update this table
- [ ] Make txfees read from this module, by looking at all entries with an osmo pool ID
- [ ] Fill in IBC information (maybe later / maybe we need to adjust items)
- [ ] Helper function for making a multi-hop through osmo pool ID, for use in cosmwasm contracts.
```

**Comment by vuong177** [comment]
I see there's a closed PR about this issue #1311 

@ValarDragon @mconcat 
Do you mind if I countinue your work and close this issue ?

**Comment by ValarDragon** [comment]
Cw-hooks solved this better
