### ISSUE TITLE
[Epic] v8 tracking issue

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1141]
- [x] Superfluid
  - [x] Import / Export working
- [x] Txfees
  - [x] Subcomponent of #1121 
    - Need non-native osmo fees going to a separate module account
  - [x] Txfees queries
- [ ] GAMM work
  - [ ] AMM interface refactor
    - [x] Main refactor done
    - [x] remaining swap methods
    - [x] #1165
    - [ ] Testing methods
    - [ ] Multihop swap fee update
  - [ ] Stableswap
    - [ ] Multi-asset
    - [ ] (Lots of testing work)
    - [ ] LP'ing code
  - [x] ~~TWAPs~~
  - [x] Governance proposals
    - [x] #1424 
- [x] Database Stability
  - [x] Pruning <> catch up 
  - [x] Pruning edge cases
  - [x] TM race condition (sufficient amount fixed)
- [x] Cosmwasm Osmosis bindings
  - [x] Bindings merged
  - [ ] Cosmwasm side API review
- [x] Agoric's vesting with clawback module
- [x] TokenFactory MVP

**Comment by ValarDragon** [comment]
It feels like to me like we're hitting scope creep on v8 / when that'd go into an on-chain proposal. I propose making a new issue for planning a v9 release, and moving some v8 items into there.

The goal would be to target a v8 proposal going on-chain April 8th or April 11th.

Items that I think we should move to v9:
* Token Factory
* TWAP

**Comment by faddat** [comment]
Kicked off a branch:

https://github.com/osmosis-labs/osmosis/tree/v8.x

**Comment by Vinitowinit** [comment]
Hey @ValarDragon, Hope your doing well mate :) Curious if this Epic will be ready by end of this week. I see @faddat has kicked off a branch which is exciting. I also see the GAMM Work still needs sometime to properly address as well!

**Comment by Vinitowinit** [comment]
Hey @ValarDragon following up here again if possible to see if there is any update. Thank you so much and enjoy the remainder of your week

**Comment by ValarDragon** [comment]
Hey, this will definitely not be ready by end of week unfortunately

**Comment by p0mvn** [comment]
Hi @Vinitowinit. 

@ValarDragon is traveling this week and might take longer to reply.

With most certainty, the epic will not be ready by the end of this week. 

The current progress on one of the largest components for v8 can be tracked here: https://github.com/osmosis-labs/osmosis/issues/1050

**Comment by Vinitowinit** [comment]
Hi yes, of course, I think I can help with documentation if need be. Improving the relevant changes I am unaware of where to help. For instance, stable swap is clearly out of my scope/capability to help :/

**Comment by mattverse** [comment]
Closing this issue in replacement of V10
