### ISSUE TITLE
[Tracking Issue] Database layer performance and stability

### ISSUE THREAD

**Issue by daniel-farina** [osmosis-labs/osmosis#1172]
**Blocked**
- [x] https://github.com/osmosis-labs/osmosis/issues/1090

**Low Priority**
- [ ] https://github.com/osmosis-labs/iavl/issues/32
- [x] #1044
   * nice to have before transitioning to rocks db
- [ ] #695
- [x] https://github.com/osmosis-labs/osmosis/issues/1140

**Tech Debt**
- [x] https://github.com/osmosis-labs/iavl/issues/25
- [x] https://github.com/osmosis-labs/iavl/issues/14

**Comment by p0mvn** [comment]
How is this different from [the epic](https://github.com/osmosis-labs/osmosis/issues/1016)?

Is it for low-priority items to be backlogged for the future?

**Comment by ValarDragon** [comment]
Sorry for the late reply, yeah thats exactly it! Wanted to get peoples thoughts on keeping epics just to the components we want to get done in a certain frame, and then keeping indexes on backlog items in these tracking issues
