### ISSUE TITLE
Major release checklist

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1494]
## Background

We need to make a major release check list. Can someone please add this to Contributing.md

- [ ] Update / cleanup changelog
- [ ] Tag release
- [ ] Update chain registry
- If major release:
  - [ ] Update all import paths and go.mod version
  - [ ] Add new backport label
  - [ ] Edit mergify config

Also someone want to take everything aside from `Tag Release` on for v8.x :sweat_smile:

**Comment by stackman27** [comment]
I can do this!

**Comment by ValarDragon** [comment]
sweet ty!
