### ISSUE TITLE
V9 Tracking Issue

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1511]
**By Wednesday, May 18th:**

- [x] #1501 
- [x] #1502 
- [x] #1503 
- [x] RC0 tagged
- [x] Testnet for integrators created

**By Friday, May 26th:**
- [x] #1191 
- [x] #1505 
- [x] #1509 
- [x] v9.0.0 released and tagged

**Saturday May 27rd:**
- [x] Gov prop created before epoch

**Wednesday June 1st:**
- [x] v9.0.0 on chain

**Optional / Non-Blocking:**
- [x] #1507 
- [x] #1510 
- [x] #1506

**Comment by mattverse** [comment]
Changed issues -> PR for the issues that have an open PR for it so that we can better track what issues are currently being worked on, what issues hasn't started
