### ISSUE TITLE
Speedup CI

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1578]
## Background

We should invest time in speeding up CI. Lots of time is lost in just waiting for CI to finish executing. If theres any reason we cannot do all of the above in github actions, imo we should investigate moving to a paid CI service, perhaps Circle, where they can all be done. Getting the feedback loop right for rapid merging multiple related PR's is important.

First where we stand on latencies. As of time of issue creation, we are blocked on:
- CodeQL (Takes 10 minutes to complete)
- Two simultaneous end to end tests (takes around 8 minutes to complete, half of which is in docker building)
- (Queued) the two go tests, each of which takes around 7 minutes to complete, half of which is spent in downloading go packages.

Furthermore, many github actions are stuck in 'queued', and take awhile before they begin execution, further increasing this dead time cost.

## Components

- [ ] Remove duplicate push / pull request jobs. #1573 , hopefully improves queue delay
- [ ] Remove less useful CLI tests (~2 minute saving on inspection of CLI logs)
- [ ] Cache Docker build
- [ ] Cache go tests #1229 
- [ ] Cache go package downloads in CI
- [ ] Figure out how to improve CodeQL times, or just remove it.

## Acceptance Criteria

- [ ] CI completes in under 5 minutes

**Comment by ValarDragon** [comment]
This repo has examples for how we can cache go package downloads in CI: https://github.com/mvdan/github-actions-golang

It also has the caching needed to get incremental builds, which would likely also help some of this CI time.

**Comment by ValarDragon** [comment]
oh thats a great idea. Perhaps we can make that variable also get run if theres any change in the upgrades sub folder as well?

**Comment by ValarDragon** [comment]
oh thats a great idea. Perhaps we can make that variable also get run if theres any change in the upgrades sub folder as well?

**Comment by ValarDragon** [comment]
For docker build times, I think we can replace the `make docker-build-debug` step with a direct docker build invocation, and use `cache` fields, e.g. https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api

**Comment by nikever** [comment]
Added the cache option in https://github.com/osmosis-labs/osmosis/pull/1602 
It gives a nice speed up but I would like to be even faster.

There are some redundant steps between `go_test` step and `e2e_test` that could be improved. 
I'm working on re-structuring a little bit the setup to avoid redoing work.
