### ISSUE TITLE
TWAP

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1599]
## Background

We want to have a fully working iteration of TWAP in v10. Preferably, TWAP is ready prior to v10 being tagged in order to be extensively tested.

## Acceptance Criteria

This is a draft writeup and will be further expanded upon.

Before June 9th:

- [x] #1650
- [ ] https://github.com/osmosis-labs/osmosis/issues/1386
- [ ] Hooks logic
  - [x] Executing at end of block for every pool that exists
- [x] Functions for TWAP math
- [x] Expose to Cosmwasm for single queries

**Comment by mattverse** [comment]
I've worked on simple TWAP implementation last year, might be somewhat familiar with TWAP. Assigning myself to this, if there's anyone willing to pair on this, lmk
