### ISSUE TITLE
v10 Tracking Issue

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#1608]
Primary v10 Features
- [x] https://github.com/osmosis-labs/osmosis/issues/1599
- [x] https://github.com/osmosis-labs/osmosis/issues/1596
- [x] https://github.com/osmosis-labs/osmosis/issues/1597
- [x] https://github.com/osmosis-labs/osmosis/issues/1598
- [x] https://github.com/osmosis-labs/osmosis/issues/1603
- [x] https://github.com/osmosis-labs/osmosis/issues/1605

Overhead (not necessarily just for v10)
- [ ] High
  - [ ] SDK branch being out of alignment with upstream
  - [ ] #1651
- [ ] Med
  - [ ] Protobuf CI
  - [ ] SDK code upstream
  - [ ] CI wait times
  - [ ] IBC denoms (raw vs hrp)
- [ ] Low
  - [ ] Lockup architecture (LockID vs lock pointer issues)
