### ISSUE TITLE
Proto message documentation

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1826]
## Background

Tracking issue for our milestone of significantly improving the documentation for each protobuf message and state entry.

Every field in every proto message should have documentation explaining what its for, and what values constitute valid input.
These can then get translated in every languages protobuf compilation, and help improve understandability.

## Modules

- [x] [x/Epochs](https://github.com/osmosis-labs/osmosis/pull/1821)
- [ ] x/gamm
- [x] [x/incentives](https://github.com/osmosis-labs/osmosis/pull/1828)
- [x] [x/lockup](https://github.com/osmosis-labs/osmosis/pull/1828)
- [x] x/mint - TODO link to PR
- [ ] x/pool-incentives
- [x] x/superfluid
- [x] x/tokenfactory
- [x] x/txfees

**Comment by p0mvn** [comment]
Based on my review only gamm and pool-incentives are still missing documentation for some messages and fields. Going to create a separate issue for each and close this one

**Comment by p0mvn** [comment]
Remaining items:
- https://github.com/osmosis-labs/osmosis/issues/2085
- https://github.com/osmosis-labs/osmosis/issues/2084
