### ISSUE TITLE
[Epic] Simulator

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1851]
## Background

Currently the simulator acts as a way of building complex state machine states, via running many messages that are expected to pass.

We want to integrate the simulator into Osmosis, but a key roadmap for us is:
* Massively reduce the boilerplate involved with simulator code
* Path to make the simulator act for fuzzing the API boundary
  * Right now we rely on our ability to perfectly predict all simulator behavior
  * Path exists to make these fuzzing learn from normal fuzzing techniques
  * Re-usability of work for unit-fuzz testing a message / operation
* More direct message scheduling capabilities
* Gain further observability into simulator state

## Suggested Simulator Design

Immediate, high impact low hanging fruit:
- [ ] Change Operation API to a new `sim simtypes.Helper, ctx sdk.Context` based API. Make `sim` federate all randomness interaction
  - [ ] We can do this in a relatively light backwards compatible API shim, if we don't want to update existing modules. (I don't want to rn)
- [x] Remove `txCtx := simulation.OperationInput{12 lines...}` with `sim`
- [ ] Architect 'smart' invariants that can declare they wish to 'wrap' a operation type. (Needed for Gamm)

Next:
- [ ] Remove tx generation management from being module responsibilities. The simulator should take in a 'tx builder' for msg -> tx (which by default can be hardcoded), and then later on developers can make variants that expose authz, feegrant, custom fee logic
- [ ] Remove weighted operations / weight management / config management from being defined at the module level. Make this something exposed at the simulator level of abstraction, with just a name for every operation.
- [ ] Begin making a fuzz API, make sim an interface that can than later be replaced with go fuzz in unit-fuzzing
- [ ] Improve operation scheduling dev UX, to have multi, state-ful messages that can act on each others results.
- [ ] Work on observability, by having every msg/tx result output into a db friendly format. (e.g. block number, tx number, action descriptor, results) all thrown into a standard SQL database we can poke around. (Maybe done by making very structured logs, that we throw into ELK)
- [ ] By federating rand access through methods, transition towards each internal method having its own derived seed, so we can tune specific components more sanely.

The dev UX for an Osmosis msg (JoinPool) with the following proto:
```protobuf
message MsgJoinPool {
  string sender = 1;
  uint64 pool_id = 2;
  string share_out_amount = 3 [(gogoproto.customtype) = "github.com/cosmos/cosmos-sdk/types.Int"];
  repeated cosmos.base.v1beta1.Coin token_in_maxs = 4;
}
```
should be
```go
func MakeJoinPoolOperation(sim simulator.Helper) Operation {
    pool_id := sim.FuzzLessThan(k.GetNextPoolId(ctx))
    sender := sim.FuzzAddrWithDenoms(k.GetPool(ctx, pool_id).Assets())
    token_in_maxs := sim.FuzzTokensSubset(sender, k.GetPool(pool_id).Assets().Denoms())
    share_out_amount := gamm.EstimateJoinPoolShareOut(ctx, pool_id, token_in_maxs)
    share_out_amount = sim.FuzzEqualInt(share_out_amount)
    
    return simtypes.NewOperationFromMsg(
        &MsgJoinPool{
            sender,
            pool_id,
            token_in_maxs,
            share_out_amount
    })
}
```
in this first pass.

At a later time, more of this should live as derivable via reflection

## Osmosis Simulator needs

(My first pass at this list)

- Gamm
  - Simulate each of the messages
    - Pre & post swap LP share amount should remain equal, CPMM `k` should only go up
  - Simulate message / inverse message pairs, from same sender, one right after the other.(Invariant that amount out less than in)
  - Swap, inverse swap, should be LTE start tokens in
- Lockup
  - Just creating and removing locks
- Superfluid
  - Simulate messages
- Incentives
  - Messages
  - Invariant wrapping epoch for "Are full incentives being distributed each day"
- Macro / mint:
  - Invariant around osmo supply at each block height

**Comment by ValarDragon** [comment]
After working on this for a few hours, I think the easiest way to write this w/ desired dev UX in mind is going to be:
* bring the simulator into Osmosis
* getting it working as I want with just simulating gamm messages
* Make it backwards compatible to support 'legacy' API

**Comment by ValarDragon** [comment]
This sprint goals for simulator:
- [ ] Complete the initial refactor
  - [ ] (Steps are mostly documented in the PR, but the main blocker is getting genesis initialization to work cleanly before and after refactor, then adding new post-refactor property check functionality)
- [ ] Add gamm operations for:
  - [ ] Spot price change before and after every swap
  - [ ] Each gamm message
  - [ ] Balancer invariant `k` increases
  - [ ] Join + Exit pool message (requires new back-end action work)

**Comment by czarcas7ic** [comment]
After discussion with Dev on the way forward with the simulator, the following points were brought up:

- Fix existing panics that occur on semi-long simulator runs
- Determine desired frequency for messages
  - A majority should just stay at default frequency, but we should determine which ones we want at a higher or lower freq
- Continue to add missing sim messages for all modules
- Improve invocation process
  - Create more makefile commands
  - Simplify go code for simulator instantiation / package complexity better
- Logging
  - Remove legacy message printfs
  - Make Param file exporting done via simulator config
  - Suppress missing validator log lines (Just edit the simlogger I made, to add this in there)
- Property check
  - https://github.com/osmosis-labs/osmosis/issues/2117
- Panic flow
  - Make panic logs easier when it panics
- Action with metadata struct
  - https://github.com/osmosis-labs/osmosis/issues/2131
- Improving genesis flow
- Improving invariance checks
  - Some checks (specifically staking/delegator-shares) slow down the sim drastically. We can make this check probabilistic to speed up the process.

**Comment by ValarDragon** [comment]
Closing for stale
