### ISSUE TITLE
Cosmwasm Tracking Issue

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#2300]
## Twap bindings

- [ ] https://github.com/osmosis-labs/osmosis/pull/2212
- [ ] https://github.com/osmosis-labs/bindings/pull/35

## Enabling whitelisted Stargate queries

- [ ] https://github.com/osmosis-labs/osmosis/pull/2190
- [ ] https://github.com/osmosis-labs/wasmd/pull/7

### Optional(tbd) 

- [ ] Support json encoding / decoding in stargate queries

**Comment by mattverse** [comment]
Closing this issue per finishing all tasks
