### ISSUE TITLE
V12 TWAP items

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#2431]
- testing
     - [ ] https://github.com/osmosis-labs/osmosis/pull/2429
     - [ ] https://github.com/osmosis-labs/osmosis/pull/2420
     - [ ] https://github.com/osmosis-labs/osmosis/pull/2364
     - [ ] https://github.com/osmosis-labs/osmosis/pull/2443
     - [ ] Property check based testing (Do we punt this to not be release blocking?) (Matt: Can we have detailed explanation on what the context is for this item?)
     - [ ] Add tests for multiple test being created in the same block (this test should go in `listeners_test.go`
     - [ ] Improve `TestAfterEpochEnd` by using `GetAllHistoricalTimeIndexedTWAPs` and `GetAllHistoricalPoolIndexedTWAPs`
