### ISSUE TITLE
Invariants meta-issue

### ISSUE THREAD

**Issue by mconcat** [osmosis-labs/osmosis#268]
meta issue for invariants

### x/gamm

- [ ] ModuleAccount balance Invariant: https://github.com/osmosis-labs/osmosis/issues/175
- [ ] Pool TotalWeight Invariant: https://github.com/osmosis-labs/osmosis/issues/144
- [ ] Spot price check Invariant: https://github.com/osmosis-labs/osmosis/issues/118
- [ ] Balancer pool reserve invariant held with spot price

### x/incentives

- [ ] ModuleAccount balance Invariant
- [ ] NonNegative TotalLocked Invariant: https://github.com/osmosis-labs/osmosis/issues/140
- [ ] Gauge iterators Invariant
- [ ] Distribution amount Invariant

### x/lockup

- [ ] ModuleAccount balance Invariant
- [ ] PeriodLock iterators Invariant
