### ISSUE TITLE
[EPIC][CL]: Concentrated Liquidity

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3014]
## Background

This is an epic to track work on concentrated liquidity (CL). While a concrete direction might still be uncertain, this issue aims to document the latest discussions.

### Introduction

We will begin by implementing the Uniswap V3 paper for the MVP. Then, we will consider changes to the existing logic.

```[tasklist]
### Concentrated Liquidity Tasks
- [ ] https://github.com/osmosis-labs/osmosis/issues/3028
- [ ] https://github.com/osmosis-labs/osmosis/issues/3029
- [ ] https://github.com/osmosis-labs/osmosis/issues/3074
- [ ] https://github.com/osmosis-labs/osmosis/issues/3991
- [ ] https://github.com/osmosis-labs/osmosis/issues/3041
- [ ] https://github.com/osmosis-labs/osmosis/issues/3042
- [ ] https://github.com/osmosis-labs/osmosis/issues/3200
- [ ] https://github.com/osmosis-labs/osmosis/issues/4027
- [ ] https://github.com/osmosis-labs/osmosis/issues/3030
- [ ] https://github.com/osmosis-labs/osmosis/issues/4424
```

## Project View

For project view, all remaining issues and milestones, please see this board:
https://github.com/orgs/osmosis-labs/projects/1/views/69

For internal audit issues, please see this board:
https://github.com/orgs/osmosis-labs/projects/1/views/74

For OtterSec audit, use this:
https://github.com/orgs/osmosis-labs/projects/1/views/75

## Scope of changes

Ordered by perceived risk:

- `x/concentrated-liquidity`
   * The module with the core CL logic
   * Completely unreleased, needs everything reviewed
- `x/superfluid`
  * Many changes related to introducing the new logic into the superfluid feature
  * Keep in mind slashing logic that happens in BeginBlock / EndBlock. Panicking here would cause chain halt.
- `x/incentives` and `x/pool-incentives`
   * Integrations of concentrated liquidity into the existing Osmosis incentives framework
   * Important content on how our CL incentives system differs from what is existing currently with balancer: https://github.com/osmosis-labs/osmosis/issues/4828
- `x/gamm`
   * This is the module containing the balancer and stableswap pool management
   * We added new migration management functionality here
- `x/poolmanager`
   * This is the module that manages pool creation, ID management and swap routing
   * It has been partially releases during the previous upgrade
   * A large portion of the changes is ported from pre-existing `x/gamm` module
   * Things to focus on (new logic):
      * [`SplitRouteExactAmountIn`](https://github.com/osmosis-labs/osmosis/blob/b933897dd5dfdc7d6c8a18a20090e3e3f6876816/x/poolmanager/router.go#L117)
      * [ `SplitRouteExactAmountOut`](https://github.com/osmosis-labs/osmosis/blob/b933897dd5dfdc7d6c8a18a20090e3e3f6876816/x/poolmanager/router.go#L388)
      * [`CreatePool`](https://github.com/osmosis-labs/osmosis/blob/b933897dd5dfdc7d6c8a18a20090e3e3f6876816/x/poolmanager/create_pool.go#L35)
- `x/twap`
   * Changes and integrations of CL into `x/twap`
- `x/protorev`
   * Module that does backrunning of swaps
   * Scope of changes: integrations into the CL module to grab highest liquidity CL pools for determining which pools to backrun
 - `x/lockup`
   * Keep in mind  BeginBlock / EndBlock lock maturity. Panicking here would cause a chain halt.
   * Module that manages locking of assets
   * Some changes stemming from superfluid integratino
- [ v16 upgrade handler logic](https://github.com/osmosis-labs/osmosis/tree/main/app/upgrades/v16)
   * This logic runs during upgrade and creates a canonical pool from the pre-existing OSMO/DAI pool

### Up-to-date

- Latest public documentation: https://github.com/osmosis-labs/osmosis/tree/main/x/concentrated-liquidity

### Diagrams

- Scope of superfluid changes

- https://lucid.app/lucidchart/c3edc266-177d-4d8d-9259-9340c1222839/edit?invitationId=inv_ccb8b41d-e744-40ef-a98c-d40d469f4397&page=0_0#
- Component Diagram & PoolManager + Gamm Refactor: https://lucid.app/lucidchart/6f0903fe-b5e9-43bc-949f-3ca3616d6e27/edit?page=0_0#

### Useful resources

- [Accumulator package](https://github.com/osmosis-labs/osmosis/tree/main/osmoutils/accum)
   * https://uploads-ssl.webflow.com/5ad71ffeb79acc67c8bcdaba/5ad8d1193a40977462982470_scalable-reward-distribution-paper.pdf
   * https://drops.dagstuhl.de/opus/volltexte/2020/11974/pdf/OASIcs-Tokenomics-2019-10.pdf
  
- [Common SDK and state-compatibility gotchas](https://github.com/osmosis-labs/osmosis/blob/main/CONTRIBUTING.md)

### Might be outdated

- Incentives: https://hackmd.io/yXK0RaJ7S2uh1m2W-OSdTw
- Trade-off space for incentives: https://hackmd.io/kJrhhh8AT2mXtCzDppkYWg
- Final Uptime Freeze Incentive Design Spec: https://hackmd.io/slJ7R-fMRjCWI1vioLcNAA
- V3 Incentive Call 14JAN23: https://hackmd.io/CHy5KkdaQFWykA7fqKaxMw
- Incentives design whiteboarding: https://hackmd.io/cJDKjFgdQu28Mdiu-bI4pw
- Geometric Tick Spacing with Additive Ranges ADR: https://hackmd.io/lUQRiQTgTkmYjDQSCV0FTg
- Accumulator API: https://hackmd.io/EUFXVr9_Roykx3jE9NNRzw
-  Breaking changes for frontend: https://hackmd.io/tMVTxXWWQju0Xis0QS5gDg
- Fee discussion: https://hackmd.io/UmXlBD9pSTav4fVi2SVnnA

## GitHub Issue Labels

- ["F: concentrated-liquidity"](https://github.com/osmosis-labs/osmosis/labels/F%3A%20concentrated-liquidity)
   * Everything associated with the CL feature
- ["cl-internal-review"](https://github.com/osmosis-labs/osmosis/issues?q=is%3Aissue+is%3Aopen+label%3Acl-internal-review)
   * Issues created during our internal review
- ["cl-ottersec-review"](https://github.com/osmosis-labs/osmosis/labels/cl-ottersec-review)
  * Issues created during OtterSec internal review

- ["cl-informal-audit"](https://github.com/osmosis-labs/osmosis/labels/cl-informal-audit)
   * Issues created during Informal internal review

## Acceptance Criteria
- concentrated liquidity MVP works

**Comment by czarcas7ic** [comment]
I am going to close this since we are now using the sprint board to track. Please feel free to re-open if you feel this provides some kind of clarity that the sprint board does not

**Comment by p0mvn** [comment]
I'm going to reopen this to keep the list of resources here for the auditors
