### ISSUE TITLE
[Story][CL]: Fees

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3074]
## Background

> As a an LP, I want to earn fees on my capital so that I am incentivized to participate in the market making actively

## Suggested Design

We will begin by implementing the Uniswap v3 paper accumulator fee model for the MVP. Next, we will consider improvements to the system

## Tasks

- [ ] https://github.com/osmosis-labs/osmosis/issues/3994
- [ ] https://github.com/osmosis-labs/osmosis/issues/3075
- [ ] https://github.com/osmosis-labs/osmosis/issues/3085
- [ ] https://github.com/osmosis-labs/osmosis/issues/3952
- [ ] https://github.com/osmosis-labs/osmosis/issues/3890
- [ ] https://github.com/osmosis-labs/osmosis/issues/3951
- [ ] https://github.com/osmosis-labs/osmosis/issues/4088
- [ ] https://github.com/osmosis-labs/osmosis/issues/3980
- [ ] https://github.com/osmosis-labs/osmosis/issues/3958
- [ ] https://github.com/osmosis-labs/osmosis/issues/3996
- [ ] https://github.com/osmosis-labs/osmosis/issues/3997
- [ ] https://github.com/osmosis-labs/osmosis/issues/3998
- [ ] https://github.com/osmosis-labs/osmosis/issues/3980
- [ ] https://github.com/osmosis-labs/osmosis/issues/4087
- [ ] https://github.com/osmosis-labs/osmosis/issues/4086
- [ ] https://github.com/osmosis-labs/osmosis/issues/4089
- [ ] https://github.com/osmosis-labs/osmosis/issues/4096

## Non-Release Blocking
- https://github.com/osmosis-labs/osmosis/issues/4005

## Acceptance Criteria
- fee tracking and distributions are implemented
- tested
- integrated into the `concentrated-liquidity` module

**Comment by p0mvn** [comment]
The last issue here is in PR
