### ISSUE TITLE
v13 tracking issue

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#3172]
## Background

- [ ] Stableswap
  - [ ] Feature completeness
  - [ ] Testing strategy / invariants reviewed
- [ ] IBC rate limit
- [ ] Swap multi-hop, having different swap fees if its osmo-routed
- [ ] Add-back bank multi-send, but with single sender
- [ ] Post handler stub added
- [ ] (Patch release actually) re-order arguments for Spot Price & TWAP functions

**Comment by mattverse** [comment]
Could I also add components that are already done & merged just to keep bettet track? eg. force unlock

**Comment by ValarDragon** [comment]
yes please
