### ISSUE TITLE
Concentrated Liquidity Chore Tracking issue

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#3178]
This Issue serves the purpose of tracking the chores needed to be done for concentrated liquidity

- [ ] Remove `currTick` from argument of `CreateNewConcentratedLiquidityPool`: we should be calculating currTick inside the method instead of having it passed on as an argument
- [ ] Make `CreateNewConcentratedLiquidityPool` return pool id instead of pool object
- [ ] Add function to mint lp shares and send coins from account to pool
- [ ] Do calculation for `MinSqrtRatio`
- [ ] #3203 
- [ ] Add logic to handle if provided sqrt price limit is 0, use min sqrt ratio and max sqrt ratio for amountSpecified(tokenIn)

**Comment by hieuvubk** [comment]
Hi @mattverse is `CreateNewConcentratedLiquidityPool` issue still needed? Id like to work with it

**Comment by p0mvn** [comment]
I'm going to close this due to being out-of-date. Most of the tasks here seem to be addressed
