### ISSUE TITLE
[WIP] Stableswap Internal Audit Tracking Issue

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#3328]
### Full Report: https://hackmd.io/juU2yglrRTyYJKJF2Tt8Pw

This tracking issue covers the list of issues that came up during our end-to-end internal review of the stableswap package in preparation for v13.

Release blocking (safety issues):
- [x] #3255 
- [x] #3277
- [x] #3254
- [x] #3353

No safety risk but either completeness issue or odd behavior:
- [x] #3355

Minor/code hygiene:
- [x] Exit single asset join early for zero input (currently runs over negative target for 1-token input)
- Fixed by #3355
- [x] Align single-asset join portion of `joinPoolSharesInternal` with all-asset portion (update error messages, variable names, and error return value)
- [x] Update error message for max stableswap numAssets (currently says 2 instead of 8)
- [x] Add comment to `maxIterations` that says to keep above 256 for it to converge
- [x] (Code hygiene) JoinPool error check
- [x] (Code hygiene) Move exit pool state update into `updatePoolLiquidityForExit`
- [x] New error message to be used in `validateScalingFactors`
- [x] Validate pool liquidity after reordering in `scaledSortedPoolReserves`
- [x] (Code hygiene) Use `p.GetTotalPoolLiquidity()` instead of raw `p.PoolLiquidity` in `getLiquidityIndexMap`
- [x] Update `cfmmConstantMultiNoV` comment to reflect that we no longer use `v` term
- [x] (Code hygiene) Switch uses of `vSumSquares` to `wSumSquares` in `cfmmConstantMulti` and `cfmmConstantMultiNoV`
- [x] Ensure calculated output leads to valid pool state in `SwapOutAmtGivenIn`
- [x] Locally defined pool update function in `calcSingleAssetJoinShares` uses `tokenIn` instead of its passed in `newLiquidity` parameter (which is remains unused)
- [x] Add "purpose" line under each function in report as docs

**Comment by AlpinYukseloglu** [comment]
All issues have been addressed!
