### ISSUE TITLE
AutoCLI Tracking Issue

### ISSUE THREAD

**Issue by pysel** [osmosis-labs/osmosis#3499]
Draft PR: https://github.com/osmosis-labs/osmosis/pull/3485

 
# Abstract

> In order to make it easier for developers to write Cosmos SDK modules, we provide infrastructure which automatically generates CLI commands based on protobuf definitions.

Due to the fact that `autocli` is already implemented in SDK (even though it does not provide much functionality yet), the main goal is to follow SDK's approach to make the same thing possible for Osmosis.

# Checklist for implementing SDK's features
- [x] `client/v2` folder <sub> (aka api types) </sub>
- [x] Add simulation run with non-related to modules commands
- [x] Add `/runtime` module to Osmosis's SDK fork
- [x] Generate proto files

# Auto CLI commands checklist by module
- [ ] Lockup  _WIP_
- [ ] Epochs
- [ ] Gamm
- [ ] Gov
- [ ] Mint
- [ ] Pool-Incentives
- [ ] Superfluid
- [ ] Tokenfactory
- [ ] TWAP
- [ ] TxFees
- [ ] Incentives

<sub>* Will create PR for each module</sub>
# Possible Problems
- Osmosis's SDK fork has _drastically_ fallen behind original SDK. Because of that a lot of additions to the current Osmosis's SDK are required. In addition, a lot of api changes will be needed because of that. At this point, I do not know wether it would be better to continue mimicking SDK's `AutoCLI` approach or rewrite it from scratch the way we need it.

-  *Dependency Injection*. As to my knowledge, Osmosis does not wish to deal with `depinject` package. This may also require to rewrite `AutoCLI` as we want, because SDK's approach uses `depinject`. However: 
   1) There is only one place using injection: injecting `AppConfig` (application configurations of every module) into `AppOptions` (application options for every module, which are needed during cobra commands generations)
   2) From conversation with SDK member, we were told that it will be possible to use it without `depinject`

These are the only problems I can think of currently. 

<sub> Will be updating this issue in time. </sub>

**Comment by ValarDragon** [comment]
Why does CLI have any need for simulation?

**Comment by RusAkh** [comment]
> Why does CLI have any need for simulation?

for the purpose of demonstrating that it works. I should have clarified that, my bad

**Comment by RusAkh** [comment]
it will only be there while it is draft, I will remove it prior to merging
that is the plan for now at least

**Comment by faddat** [comment]
@ValarDragon splice into the osmosis-sdk, or work on a v47 upgrade?

Getting reports currently that bringing autocli into sdk v45, will cause breakages when Osmosis moves to cosmos-sdk v0.47.*

**Comment by RusAkh** [comment]
> @ValarDragon splice into the osmosis-sdk, or work on a v47 upgrade?
> 
> Getting reports currently that bringing autocli into sdk v45, will cause breakages when Osmosis moves to cosmos-sdk v0.47.*
> 
> Today's workshop is on autocli again, so we're all poking at it currently.
> 
> ## What doesn't work
> * app wiring related features
> 
> * what does
>   
>   * autocli itself

I'd say autocli does not work due to app-wiring absence in sdk45 of osmosis

**Comment by faddat** [comment]
Okay, let's do what the SDK team recommended, and table this for a little bit. Let's keep your research at the ready and thank you so much for really digging deep into this.

**Comment by ValarDragon** [comment]
Should we close this for now, in favor of `osmocli`?
