### ISSUE TITLE
tracking(CL): merge to main

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#3556]
## Background

This issue is for tracking the progress of merging `concentrated-liqudiity-main` to main.

As we are merging in chunks with the goal of splitting state-break logic from state-compatible, we end up commenting out some functionality and tests.

This issue tracks these areas to make sure nothing is left uncommented

## TODOs

- [x] `x/swaprouter/types`
   * [x] merge in `codec.go`
   * [x] uncomment authz test: https://github.com/osmosis-labs/osmosis/blob/bc4ed47025b5a363d5e3194f981eb15d1b6ecbff/x/swaprouter/types/msgs_test.go#L279-L280
   * [x] uncomment `GetSizeBytes()` for `MsgSwapExactAmountIn`: https://github.com/osmosis-labs/osmosis/blob/bc4ed47025b5a363d5e3194f981eb15d1b6ecbff/x/swaprouter/types/msgs.go#L43
   * [x] uncomment `GetSizeBytes()` for `MsgSwapExactAmountOut`: https://github.com/osmosis-labs/osmosis/blob/bc4ed47025b5a363d5e3194f981eb15d1b6ecbff/x/swaprouter/types/msgs.go#L83
   * godoc: https://github.com/osmosis-labs/osmosis/pull/3764/files#r1052738361

- `x/swaprouter/cli`
   * re-enable cli tests: https://github.com/osmosis-labs/osmosis/pull/3557/files#r1034133974
   * re-enable query tests: https://github.com/osmosis-labs/osmosis/pull/3557/files#r1034134838

- [x] x/swaprouter/module`
   * merge module.go to enable type registrations and simulation
          * [x] https://github.com/osmosis-labs/osmosis/pull/3557/files#r1034136480
          * [x] https://github.com/osmosis-labs/osmosis/pull/3557/files#r1034137022

- [x] `x/swaprouter`
   * re-enable: https://github.com/osmosis-labs/osmosis/pull/3557/files#r1034135904

- [x] `app/keepers/keepers.go`
   * remove and initialize keeper: https://github.com/osmosis-labs/osmosis/blob/72925e82fae4106d36d67828b32ab752fe4a123a/app/keepers/keepers.go#L124-L125

- [x] `x/gamm/simulation`:
   * move pool creation fee to swaprouter simulation: https://github.com/osmosis-labs/osmosis/pull/3738#discussion_r1050093787

- `x/gamm`
    * remove nolint from `convertToCFMMPool`
    * deprecate `NumPools` query and implement it in `x/swaprouter`
    * address TODO: https://github.com/osmosis-labs/osmosis/pull/3764#discussion_r1052776763

**Comment by p0mvn** [comment]
This comment is for tracking PRs merged to `concentrated-liqudity-main` after the merge has started. Feel free to edit
- https://github.com/osmosis-labs/osmosis/pull/3687 - some logic in swaprouter's `CreatePool`

**Comment by czarcas7ic** [comment]
Added concentrated liquidity test to the swaprouter module in the following PR: https://github.com/osmosis-labs/osmosis/pull/3733

See https://github.com/osmosis-labs/osmosis/pull/3733/files/0083c205e4d359aaaa2129f2a160087a02571524#r1049147785

Also added the concentratedLiquidityKeeper type to the router_test.go file as a variable

**Comment by p0mvn** [comment]
CL module merge removals that need to be re-added:
- wire up keeper: https://github.com/osmosis-labs/osmosis/pull/3877/files#r1058527923

Tests:
- https://github.com/osmosis-labs/osmosis/pull/3877/files#r1058528099
- https://github.com/osmosis-labs/osmosis/pull/3877/files#r1058528177
- https://github.com/osmosis-labs/osmosis/pull/3877/files#r1058528434

Codec removals:
- https://github.com/osmosis-labs/osmosis/pull/3877/files#r1058528634
- https://github.com/osmosis-labs/osmosis/pull/3877/files#r1058528726
- https://github.com/osmosis-labs/osmosis/pull/3877/files#r1058528826
- https://github.com/osmosis-labs/osmosis/pull/3877/files#r1058528952

**Comment by p0mvn** [comment]
Using this comment as a sanity check on what TODOs have been complete:
- `x/swaprouter/types` codec changes: https://github.com/osmosis-labs/osmosis/pull/3912

**Comment by p0mvn** [comment]
All TODOs here have been addressed. The only remaining one is kept in code as TODO since it is non-blocking:
- https://github.com/osmosis-labs/osmosis/pull/3764#discussion_r1052776763
