### ISSUE TITLE
osmocli epic:

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#3641]
OsmoCli (#3611) roadmap of things to tackle to improve testing UX:
- [x] Add the ability to register a custom parser for a given field. (Lets us eliminate the rest of existing boilerplate / non-converted funcs)
- [x] Add some go tests within osmo-cli
- [x] Change the syntax from cmd.AddCommands to instead be osmocli.AddTx[M sdk.Msg](&TxDesc, msg M)
  - [x] Need to figure out how to register custom flagsets in this syntax 
  - [x] Lets us make a second method, for getting a proto-parser from desc, and then we can kill all the current slow CLI tests
- [ ] README
- [x] Split this into its own go.mod, so others can import

**Comment by RusAkh** [comment]
hello @ValarDragon. I would like to collaborate here, is it ok with you?
