### ISSUE TITLE
ABCI Tracking Issue

### ISSUE THREAD

**Issue by alexanderbez** [osmosis-labs/osmosis#3668]
## Context

Once Osmosis' SDK `[feature/abci-1.0](https://github.com/osmosis-labs/cosmos-sdk/tree/feature/abci-1.0)` lands (and tagged) into `osmosis-main`, we need to handle a few things on Osmosis for feature completeness:

## Tasks (v15)

- [ ] Implement `PrepareProposal` handler.
  - This handler is responsible for iterating over all `txs` and executing a nonce validation check, rejecting (i.e. not including) any invalid txs (by nonce) in the response.
- [ ] Implement `ProcessProposal` handler.
  - This handler performs the same responsibility/function as `PrepareProposal` except it is execute by _ALL_ validator processes.

Note, a custom will _NOT_ be used, as we'll rely on Tendermint's FIFO ordering provided to `RequestPrepareProposal`.

## Future Tasks (v16+)

- [ ] Implement top of block/batch auctioning.
  - The idea here is that users can specify a batch auction fee in a tx. In `PrepareProposal`, a proposer scans for any existence of these txs in `RequestPrepareProposal`. If any exist, a proposer includes the highest bid tx as the 1st tx in the block proposal and rejects ALL others with a bid for that particular proposal/block. There are corner cases and some nuances we'll need to address, but this is the gist of it.
- [ ] R&D into discovery of "faulty" Osmosis processes.
  - i.e. discovering validators that are running a custom mempool and/or `PrepareProposal` handler and what should be done about it. (cc @czarcas7ic)

cc @ValarDragon @sunnya97 @p0mvn @czarcas7ic
