### ISSUE TITLE
List of code changes to upstream to the cosmos-SDK

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#377]
We've accumulated several changes that we should be upstreaming back to the cosmos SDK. I want to use this issue to track this. We should start making plan for converging the upstreams for these as we get more engineering capacity. Lets edit this PR as we accumulate more, so we can at least remember everything to do here

- [x] Mutative Decimal operations (cref https://github.com/cosmos/cosmos-sdk/issues/9046)
- [ ] Min commission rate work (cref https://github.com/cosmos/cosmos-sdk/pull/9245 )
- [ ] Simulation infrastructure work (I believe marko helped upstream some / maybe all of this? I'll need to double check. Maybe some items from https://github.com/cosmos/cosmos-sdk/issues/9443 are still left)
- [ ] More substantitive bank genesis simulation: https://github.com/osmosis-labs/cosmos-sdk/pull/9
- [x] Governance hooks (https://github.com/osmosis-labs/cosmos-sdk/pull/2 ) potentially upstreamed already?
- [ ] See if AddToOriginalVestingCoins (https://github.com/osmosis-labs/cosmos-sdk/commit/7c30092d1c8cf52dd1af318e73bd7cacf4aa775b) is desired
- [ ] Ask if the entire epochs module once stable / more documented would like to live in the SDK (https://github.com/osmosis-labs/osmosis/tree/main/x/epochs), likely blocked on #149 #192, and maybe hook infra work for #152 
- [ ] Move our code for `debug secp-pubkey` into the default `pubkey` command, and upstream
- [x] Display all module account addresses

**Comment by ValarDragon** [comment]
This issue is pretty unmaintained. Going to close this for now,
