### ISSUE TITLE
[Story][CL]: Simulator testing for concentrated liquidity

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4027]
## Background

> As an engineer, I would like to have randomized testing for concentrated liquidity, so that I can be more confident that the core logic works as expected under various situations

## Suggested Design

Implement a simulator for all concentrated liquidity messages, that would be similar with the gamm simulator( cref: https://github.com/osmosis-labs/osmosis/tree/main/x/gamm/simulation)

## Tasks

We want to have the following components tested via simulator

- [x] - Random Create Position Msg  https://github.com/osmosis-labs/osmosis/pull/4185
- [x] - Random Withdraw Position Msg https://github.com/osmosis-labs/osmosis/pull/4185
- [x] - Random create concentrated liquidity pool https://github.com/osmosis-labs/osmosis/pull/4094
- [ ] - RandomSwapExactAmountIn https://github.com/osmosis-labs/osmosis/pull/4241
- [ ] - RandomSwapExactAmountOut https://github.com/osmosis-labs/osmosis/pull/4241
- [x] - Random CollectFees  https://github.com/osmosis-labs/osmosis/pull/4185

We also want to add simulator testings for the pool manager module if possible

## Acceptance Criteria
- simulator is implemented for concentrated liquidity
- all messages are tested

**Comment by p0mvn** [comment]
Hi @stackman27. Could you please break this down into tasks?

**Comment by stackman27** [comment]
yup will do apologies for the delay

**Comment by stackman27** [comment]
#4241 blocked by https://github.com/osmosis-labs/osmosis/issues/4366

**Comment by p0mvn** [comment]
Addressed now
