### ISSUE TITLE
[CL Fees]: Fee - Misc tracking issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4096]
## Background

This issue consists of misc TODOs that we should revisit before finalizing the fees user story.

## Suggested Design

- [x] index positions by strings in the accum module. Make sure that CL
  positions are indexed by pool, owner and tick range.
- [x] make sure accumulator module allows for prefixes that preserve data locality.
- [x] try moving fees logic into the internal package
- [x] figure out how to make calcs non-mutative
- [x] make sure fees are updated in the right places
- [x] document that if we withdraw all shares, the rewards are claimed and the
fee accumulator position is deleted. As a result, next time we add liqudity for the same
ticks, we need to re-initialzie the 
- [x] remove prints for swaps

## Acceptance Criteria
- all TODOs above are addressed

**Comment by p0mvn** [comment]
Additional tracking:
- https://github.com/osmosis-labs/osmosis/pull/4249#discussion_r1100345811
- https://github.com/osmosis-labs/osmosis/pull/4249#discussion_r1100346638
- https://github.com/osmosis-labs/osmosis/pull/4249#discussion_r1100346863

**Comment by p0mvn** [comment]
Confirmed that all TODOs are either addressed or obsolete
