### ISSUE TITLE
[v16]: Scoping issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4700]
## Background

This is a tracking issue for the v16 release. The rough expected release date is early to mid-June. We will update this tracking issue as the scope becomes clearer

## Scope

```[tasklist]
### Features
- [ ] #3014
- [ ] #4389
- [ ] https://github.com/osmosis-labs/osmosis/issues/4444
- [ ] https://github.com/osmosis-labs/osmosis/issues/5044
- [ ] https://github.com/osmosis-labs/osmosis/pull/4629
```

```[tasklist]
### Protorev PRs
- [ ] #4829
- [ ] #4827
- [ ] #4826
- [ ] https://github.com/osmosis-labs/osmosis/pull/4878
- [ ] https://github.com/osmosis-labs/osmosis/issues/4997
```

```[tasklist]
### Dependency Updates
- [ ] #4677
- [ ] #4964
- [ ] https://github.com/osmosis-labs/osmosis/issues/5255
- [ ] https://github.com/osmosis-labs/osmosis/issues/5256
- [ ] https://github.com/osmosis-labs/osmosis/issues/5273
```

```[tasklist]
### Gov props
- [ ] #4371
```

```[tasklist]
### Tests
- [ ] #4703
```

```[tasklist]
### Misc
- [x] https://github.com/osmosis-labs/osmosis/issues/5041
- [ ] https://github.com/osmosis-labs/osmosis/issues/5272
- [ ] https://github.com/osmosis-labs/osmosis/issues/5258
- [ ] https://github.com/osmosis-labs/osmosis/issues/5259
```

## Acceptance Criteria
- all planned updates are merged in
