### ISSUE TITLE
CosmWasm Pool: Misc Tracking issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4765]
## Background

This is a tracking issue of misc TODOs left in PRs.

## Acceptance Criteria

- [ ] Decide if module parameters are needed and remove them if not
- [ ] Decide if message server is needed and remove it if not
- [ ] Remove nolints: https://github.com/osmosis-labs/osmosis/pull/4764#discussion_r1149957231
- [ ] Uncomment state-break in `msgs.go`: https://github.com/osmosis-labs/osmosis/pull/4764#discussion_r1149957434
- [ ] Uncomment pool constructor: https://github.com/osmosis-labs/osmosis/pull/4764#discussion_r1149957514
- [ ] Validation of `MsgCreateCosmWasmPool`

**Comment by p0mvn** [comment]
Duplicate of: https://github.com/osmosis-labs/osmosis/issues/5329
