### ISSUE TITLE
ProtoRev v16 Tracking Issue (DRAFT)

### ISSUE THREAD

**Issue by NotJeremyLiu** [osmosis-labs/osmosis#4997]
## Background

Tracking issue for all things related to ProtoRev for v16 upgrade

Concentrated Liquidity Module Changes:
- [ ] https://github.com/osmosis-labs/osmosis/pull/4950

Poolmanager Module Changes:
- [ ] https://github.com/osmosis-labs/osmosis/pull/4946

Protorev Module Changes:
- [ ] https://github.com/osmosis-labs/osmosis/pull/4827
- [ ] https://github.com/osmosis-labs/osmosis/tree/jl/protorev-hook-based-logic

**Comment by p0mvn** [comment]
Hi @NotJeremyLiu . Is this up-to-date?

**Comment by NotJeremyLiu** [comment]
Hey @p0mvn ,

This is up to date.

I still need to turn the hook-based logic from a branch into a PR (need to add tests still), and the dev fee payout / updating is ready for review from Osmosis side (will add some comments on the PR to focus on a point that I would like extra eyes on.

**Comment by NotJeremyLiu** [comment]
Looks like I need to tackle some conflict issues now with https://github.com/osmosis-labs/osmosis/pull/4827, can tackle tomorrow

**Comment by p0mvn** [comment]
Sweet. Thanks for the update

**Comment by NotJeremyLiu** [comment]
@p0mvn the two PRs in this issue are r4r now, added comments in the https://github.com/osmosis-labs/osmosis/pull/4827 specifically would appreciate a focus on how the upgrade is handled, as I believe it is incorrect (e2e tests fail) but am at my limit of knowledge of how to fix it.

**Comment by p0mvn** [comment]
Thanks for the update @NotJeremyLiu . @stackman27 is looking into the e2e issue

**Comment by czarcas7ic** [comment]
Removing this tracking issue from sprint 32 since we are tracking the sub components in this sprint
