### ISSUE TITLE
V17: Scoping Issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5191]
## Background

Tentative plan for the v17 scope. Each effort is to have a design document created. Upon reviewing and accepting the design, the final decision about v17 inclusion will be made.

Note: hackmd with post-CL plans: https://hackmd.io/FOlDt6H7QlqyabBYhZVxMQ

* Async ICQ (Dev/Nicholas)
* Full power token factory (Matt)
* Protorev (Skip)
* Msg to break lock, swap to osmo, then stake (Matt)

## In-Scope

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/5446
- [ ] https://github.com/osmosis-labs/osmosis/issues/5812
- [ ] https://github.com/osmosis-labs/osmosis/issues/5858
- [ ] https://github.com/osmosis-labs/osmosis/issues/5867
- [ ] https://github.com/osmosis-labs/osmosis/issues/5842
- [ ] https://github.com/osmosis-labs/osmosis/issues/5854
- [ ] https://github.com/osmosis-labs/osmosis/pull/5072
- [ ] https://github.com/osmosis-labs/osmosis/issues/5868
- [ ] https://github.com/osmosis-labs/osmosis/pull/5863
- [ ] https://github.com/osmosis-labs/osmosis/issues/5630
- [ ] https://github.com/osmosis-labs/osmosis/issues/5888
- [ ] https://github.com/osmosis-labs/osmosis/issues/5892
- [ ] https://github.com/osmosis-labs/osmosis/issues/5894
- [ ] https://github.com/osmosis-labs/osmosis/issues/5898
- [ ] https://github.com/osmosis-labs/osmosis/pull/4252
- [ ] https://github.com/osmosis-labs/osmosis/pull/5861
- [ ] https://github.com/osmosis-labs/osmosis/issues/5725
- [ ] Stride change scalling factor gov acc
- [ ] https://github.com/osmosis-labs/osmosis/pull/5927
```
## To Be Decided if included in v17
```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/5928
```

## Not Release Blocking

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/5845
```

## Concurrent To v17

Efforts being pursued concurrently but independently of v17 release

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/5736
- [ ] https://github.com/osmosis-labs/osmosis/issues/5737
- [ ] https://github.com/osmosis-labs/osmosis/issues/4344
```

**Comment by faddat** [comment]
I think that if v17 is on sdk 48, ibc will be at v8.  Kind of a nit, but I think that'll be the case.  

Can you run me through POB and volume based incentives? 

Generally, we've been advising that chain upgrades to a new sdk version do not add features.  How would you feel about doing this as a v17, then a v18 shortly after, with POB and volume based incentive splitting?

**Comment by faddat** [comment]
Okay so I figured out that POB is the protocol owned builder from Skip and that sounds awesome, I'm currently upgrading IBC to SDK 50 and I guess I'd like to ask @ValarDragon If his stance has changed on using dependency injection in osmosis, not using it is really looking pretty baroque.

**Comment by p0mvn** [comment]
> I think that if v17 is on sdk 48, ibc will be at v8. Kind of a nit, but I think that'll be the case.
> 
> Can you run me through POB and volume based incentives?
> 
> Generally, we've been advising that chain upgrades to a new sdk version do not add features. How would you feel about doing this as a v17, then a v18 shortly after, with POB and volume based incentive splitting?
> 
> Also please note that I'm adding stuff to the issue above, lmk if that's alright.
> 
> * [lint all tests #5127](https://github.com/osmosis-labs/osmosis/pull/5127)

Sorry for the late reply.

> I think that if v17 is on sdk 48, ibc will be at v8

Sounds great, thanks for the info. We haven't started investigating yet as we've been busy with CL. Will look more into it in a few weeks.

> How would you feel about doing this as a v17, then a v18 shortly after, with POB and volume based incentive splitting?

Generally, we are supportive of smaller releases at a faster cadence. This issue's main goal is to track the next immediate priorities and what we want in v17. Before we fully converge on the scope, a design document will be written for each item identified here. Once the design documents shed light on the overall scope, we will make a decision on what the final v17 will look like.

> Can you run me through POB and volume based incentives?

Looks like POB is already resolved. Volume-based incentives is a system to incentivize a denom pair assuming that there are 2 pools for the same pair such as classic and CL pool. Then, the distribution to each of the pools will be dynamically split based on volume.

> Also please note that I'm adding stuff to the issue above, lmk if that's alright.

Let's not add lints here please and use this issue for tracking release blocking items instead. 
We can get in the lint improvements but they don't necessarily have to block the v17 release

**Comment by faddat** [comment]
@p0mvn great point about the lints. 

I try and do them before upgrades to make the upgrade easier becasue the upgrade tends to break a lot of things, but you're right they absolutely shouldn't block a release. 

Want to have a call sometime next week in order to figure out what the unfork should look like?

**Comment by faddat** [comment]
@p0mvn -- here's an update of ibc-go 

* https://github.com/notional-labs/ibc-go/pull/214
