### ISSUE TITLE
[Epic] SDK Unfork

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5724]
Background

Design doc owner: @czarcas7ic 

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/6097
- [ ] https://github.com/osmosis-labs/osmosis/issues/6099
- [ ] https://github.com/osmosis-labs/osmosis/issues/6027
```

Acceptance Criteria

Design document created
Implemented
