### ISSUE TITLE
ProtoRev v17 Improvements Tracking

### ISSUE THREAD

**Issue by NotJeremyLiu** [osmosis-labs/osmosis#5858]
## Background

Tracking issue for protorev improvements to land in v17 upgrade.

Required - State Breaking
- [x] #5841 
- [x] Address concentrated liquidity tick bounding during rebalance (https://github.com/osmosis-labs/osmosis/issues/5884) #5930
- [x] Add cosmwasm pool type to pool points #5901 
- [ ] Add testing for gas estimation and time execution on CW pools #5948
- [ ] Ability to set maxTicksCrossed via a message #5948

Nice to have - State Breaking
- [ ] Check for 2 pool routes to rebalance via highest liquidity method #5953

Nice to have - State Compatible
- [x] #5870
- [x] #5862 

Nice to have - Research
- [ ] Look more deeply into cosmwasm pool type and if custom logic needs to be built to handle these pools better (similar to how we need to special case handle CL pools, pool weight, etc)

De-prioritized:
- [ ] Improve ante handle abstraction to allow for more granular gas limit testing, resolving this comment: https://github.com/osmosis-labs/osmosis/pull/5841#discussion_r1267306903 (not pursued, will be for next upgrade or patch)

**Comment by davidterpay** [comment]
Going to add some tasks for testing CW pools.

**Comment by NotJeremyLiu** [comment]
Leaving as a comment to flag: Do we want to bump the max gas limit for protorev posthandler to 100 mil rather than 50 mil? Or any other number?
