### ISSUE TITLE
V20: Scoping Issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5864]
## Background

Tentative plan for the v20 scope. Each effort is to have a design document created. Upon reviewing and accepting the design, the final decision about v20 inclusion will be made.

## Need Decision

Issues that were requested and need scope decisions

```[tasklist]
```

## In-Scope
The scope that is currently planned for v20

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/6541
- [ ] https://github.com/osmosis-labs/osmosis/issues/6057
- [ ] https://github.com/osmosis-labs/osmosis/pull/4713
- [ ] https://github.com/osmosis-labs/osmosis/issues/6330
- [ ] https://github.com/osmosis-labs/osmosis/issues/6345
- [ ] https://github.com/osmosis-labs/osmosis/issues/6373
- [ ] https://github.com/osmosis-labs/osmosis/issues/6482
- [ ] https://github.com/osmosis-labs/osmosis/pull/5967
- [ ] https://github.com/osmosis-labs/osmosis/pull/6630
- [ ] IBC version bump https://github.com/cosmos/ibc-go/releases/tag/v4.5.0
- [x] Taker fee bypass
- [ ] https://github.com/osmosis-labs/osmosis/pull/6627
- [ ] https://github.com/osmosis-labs/osmosis/issues/6645
```

## Non-Blocking

Efforts below will be added to the scope if they are complete prior to the current scope being complete.

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/5726
- [ ] https://github.com/osmosis-labs/osmosis/issues/5606
- [ ] https://github.com/osmosis-labs/osmosis/issues/5969
- [ ] https://github.com/osmosis-labs/osmosis/issues/6340
```

## Not Pursuing

Efforts below are not being pursuit this release.

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/6390
- [ ] https://github.com/osmosis-labs/osmosis/issues/6389
- [ ] https://github.com/osmosis-labs/osmosis/issues/6544
```

## Concurrent To v20

Efforts being pursued concurrently but independently of v20 release

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/6255
- [ ] https://github.com/osmosis-labs/osmosis/issues/5736
- [ ] https://github.com/osmosis-labs/osmosis/issues/5737
- [ ] https://github.com/osmosis-labs/osmosis/issues/4344
```

## Deprioritized

Issues below were in-scope at some point but were moved out due to a lack of clarity on product priorities.

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/pull/5861
- [ ] https://github.com/osmosis-labs/osmosis/issues/5630
- [ ] https://github.com/osmosis-labs/osmosis/pull/4252
- [ ] https://github.com/osmosis-labs/osmosis/issues/6122
```

**Comment by faddat** [comment]
@p0mvn I think that once v17 is in, reasonable to kick off on this.  I'm also going to close some older issues on this topic.

**Comment by p0mvn** [comment]
Cross-posting from Slack:

Hi Jacob.

Thanks for the context.

This is my first day back from vacation so I don't have the most up-to-date context on the plans for the unfork. Will share my latest state below and get back with updates once I have them.

The current plan is to focus on releasing v17 with immediate concentrated liquidity fixes and improvements.
Only after that, we will dedicate capacity on writing up a design document with plans for the unfork, including how it will relate to all the dependencies.

As part of concentrated liquidity learnings, we would like to avoid using feature branches due to branch synching overhead. So if you are able to start some smaller incremental work, please do it to main as opposed to long-lasting feature branches.
Additionally, we now have a requirement to create a document outlining all known context and development plan before starting on the actual implementation of a large feature. The reason why this is especially important for unfork is because we will need to figure out how to deal with some of the custom functionality on our fork. For SDK unfork, Adam, Nicolas and I will be working on it after v17 is out. Once it's ready, we are hoping to collaborate on the implementation with anyone interested.
That being said, if you can drive forward some of the dependency upgrades in the meantime such as wasmd etc, so that they are compatible with sdk 0.50, that would be excellent.

AFAIR, the only reason we use our custom wasmd is because we have some custom SDK fork APIs that prevent us from using the upstream. Will need to confirm this. Ideally, we should stop using Osmosis fork for wasmd as well after unforking SDK
