### ISSUE TITLE
v17: release process improvements and chores

### ISSUE THREAD

**Issue by niccoloraspa** [osmosis-labs/osmosis#5904]
## Background

This is a tracking issue, to track some release process and general QoL improvements that I would like to introduce from this release.

v17 scoping issue remains: https://github.com/osmosis-labs/osmosis/issues/5191

### Improvements

- [x] Introduce go releaser to manage the release (https://github.com/osmosis-labs/osmosis/pull/5813) 
- [x] Add `goreleaser` commands to Makefile  and create a Github Action to run `goreleaser` https://github.com/osmosis-labs/osmosis/pull/5908
- [x] Create a script to generate `binaries.json` from a release https://github.com/osmosis-labs/osmosis/pull/5907
- [x] Update [chain-registry](https://github.com/osmosis-labs/osmosis/blob/main/chain.schema.json) with all information about releases https://github.com/osmosis-labs/osmosis/tree/main/networks/osmosis-1/upgrades https://github.com/osmosis-labs/osmosis/pull/5910
- [x] Update `cosmovisor.json` in all previous versions: 
- [ ] Remove outdated docs in https://github.com/osmosis-labs/osmosis/tree/main/networks/osmosis-1/upgrades
- [ ] Create a GitHub action to automatically update the chain registry schema when a release is published.
- [ ] Create a GitHub action to automatically update the osmosis installer when a release is published.
