### ISSUE TITLE
v21: Scoping Issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#5970]
## Background

Tentative plan for the v19 scope. Each effort is to have a design document created. Upon reviewing and accepting the design, the final decision about v19 inclusion will be made.

## Need Decision

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/2791
- [ ] https://github.com/osmosis-labs/osmosis/issues/6582
- [ ] https://github.com/osmosis-labs/osmosis/issues/6580
- [ ] https://github.com/osmosis-labs/osmosis/issues/6705
- [ ] https://github.com/osmosis-labs/osmosis/issues/6726
- [ ] https://github.com/osmosis-labs/osmosis/issues/6862
- [ ] https://github.com/osmosis-labs/osmosis/issues/6873
```

## In-Scope

The scope that is currently planned for v21

```[tasklist]
- [ ] LOOT
```

## Progress Dependent

Efforts below will be released as soon as complete, potentially affecting the release scope.

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/5724
- [ ] POB v1.0.0
```

## TBD

```[tasklist]
- [ ] Account Abstraction
- [ ] Governance improvement
- [ ] Trade batching
```

**Comment by sunnya97** [comment]
Why is LOOT something that is dependent on a chain release? I thought it was all in CosmWasm?
