### ISSUE TITLE
Volume Splitting Incentives Tracking Issue

### ISSUE THREAD

**Issue by AlpinYukseloglu** [osmosis-labs/osmosis#6057]
Note: the formatting on this issue seems to be getting constantly cleared by our clickup integration

Overview

This is a tracking issue intended to cover all the remaining open issues related to volume splitting incentives. Please note that while this feature implements a simple mechanism, the implementation still has a number of moving parts to ensure code hygiene and forward compatibility with future splitting policies we might want to add.

TDD: https://docs.google.com/document/d/1gF50VwO3Qxdz9f-PFCLUbwUCBFbVfUspoXdBni9lzWM/edit

This issue is also intended to be more in depth than #5723, which seems to have been a high level issue created while we were deciding scope for v18.

## Remaining Tasks

```[tasklist]

```

## Completed Tasks

```[tasklist]
- [ ] #6089
- [ ] #6090
- [ ] #6091
- [ ] #6092
- [ ] #6093
- [x] Implement GroupGauge struct
- [ ] https://github.com/osmosis-labs/osmosis/issues/6402
- [ ] https://github.com/osmosis-labs/osmosis/issues/6432
- [ ] https://github.com/osmosis-labs/osmosis/issues/6433
- [ ] https://github.com/osmosis-labs/osmosis/issues/6405
- [ ] https://github.com/osmosis-labs/osmosis/issues/6434
- [ ] https://github.com/osmosis-labs/osmosis/issues/6159
- [ ] https://github.com/osmosis-labs/osmosis/issues/6401
- [ ] https://github.com/osmosis-labs/osmosis/issues/6404
- [ ] https://github.com/osmosis-labs/osmosis/issues/6500
- [ ] https://github.com/osmosis-labs/osmosis/issues/6505
- [ ] https://github.com/osmosis-labs/osmosis/issues/6501
- [ ] https://github.com/osmosis-labs/osmosis/issues/6499
- [ ] https://github.com/osmosis-labs/osmosis/issues/6155
- [ ] https://github.com/osmosis-labs/osmosis/issues/6507
- [ ] https://github.com/osmosis-labs/osmosis/issues/6513
- [ ] https://github.com/osmosis-labs/osmosis/issues/6508
- [ ] https://github.com/osmosis-labs/osmosis/issues/6545
- [ ] https://github.com/osmosis-labs/osmosis/issues/6526
- [ ] https://github.com/osmosis-labs/osmosis/issues/6573
- [ ] https://github.com/osmosis-labs/osmosis/issues/6558
- [ ] https://github.com/osmosis-labs/osmosis/issues/6506
- [ ] https://github.com/osmosis-labs/osmosis/issues/6557
- [ ] https://github.com/osmosis-labs/osmosis/issues/6576
- [ ] #6153
- [ ] https://github.com/osmosis-labs/osmosis/issues/6559
- [ ] https://github.com/osmosis-labs/osmosis/issues/6581
- [ ] https://github.com/osmosis-labs/osmosis/issues/6577
- [ ] https://github.com/osmosis-labs/osmosis/issues/6592
- [ ] https://github.com/osmosis-labs/osmosis/issues/6593
- [ ] https://github.com/osmosis-labs/osmosis/issues/6603
- [ ] https://github.com/osmosis-labs/osmosis/issues/6602
- [ ] https://github.com/osmosis-labs/osmosis/issues/6443
- [ ] https://github.com/osmosis-labs/osmosis/issues/6154
```
