### ISSUE TITLE
[EPIC] Account Abstraction

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis#6075]
## Background

This is a tracking issue for the Account Abstraction

## Suggested Design

https://hackmd.io/vRbItUUUSs2dALdYQXIx-Q

### V1

Initial implementation and classic authenticator

## Acceptance Criteria

```[tasklist]
### V1 Tasks
- [ ] https://github.com/osmosis-labs/osmosis/issues/6076
- [ ] https://github.com/osmosis-labs/osmosis/issues/6077
- [ ] https://github.com/osmosis-labs/osmosis/issues/6078
- [ ] https://github.com/osmosis-labs/osmosis/issues/6079
- [ ] https://github.com/osmosis-labs/osmosis/issues/6080
- [ ] https://github.com/osmosis-labs/osmosis/issues/6081
- [ ] https://github.com/osmosis-labs/osmosis/issues/6082
- [ ] https://github.com/osmosis-labs/osmosis/issues/6126
- [ ] https://github.com/osmosis-labs/osmosis/issues/6127
- [ ] https://github.com/osmosis-labs/osmosis/issues/6128
- [ ] https://github.com/osmosis-labs/osmosis/issues/6129
- [ ] https://github.com/osmosis-labs/osmosis/issues/6130
- [ ] https://github.com/osmosis-labs/osmosis/issues/6313
- [ ] https://github.com/osmosis-labs/osmosis/issues/6377
```

**Comment by ValarDragon** [comment]
Should we close this? I think we track AA work differently
