### ISSUE TITLE
[VS Incentives] Post-launch tracking issue

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#6635]
## Non-blocking

```[tasklist]
- [ ] https://github.com/osmosis-labs/osmosis/issues/6556
- [ ] https://github.com/osmosis-labs/osmosis/issues/6540
- [ ] https://github.com/osmosis-labs/osmosis/issues/6400
- [ ] https://github.com/osmosis-labs/osmosis/issues/6572
- [ ] https://github.com/osmosis-labs/osmosis/issues/6546
- [ ] https://github.com/osmosis-labs/osmosis/issues/6591
- [ ] https://github.com/osmosis-labs/osmosis/issues/6590
```

## Acceptance Criteria
- Follow-ups completed
