### ISSUE TITLE
WIP: Interfluid staking sub-component tracking

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#705]
Interfluid staking is allowing a user to use their OSMO <> $A token LP shares, and stake both the osmo component and $A component of their LP shares.

For a v1, I suggest we have all validators get the same reward rate per unit stake, and punt distinct reward rates per validator to a v2. This is because all cosmos chains atm have validator rewards only differ in proposer bonus of inflation minting' (centralizing), and tx fees (negligible impact atm).

I also suggest all delegation rewards getting distributed on Osmosis. Doing delegation rewards on the other chain requires very high cross-chain communication complexity. We can extend our airdrop tooling to make this easier for folks.

We should make two new modules, `x/interfluid_staking` that chain A uses, and `x/interfluid_custodian` that Osmosis uses.

Subset of steps needed:
- IBC communications
  - [ ] Get all of chain A's active validators over IBC.
    - [ ] Needs moniker + valoperaddress
  - [ ] Make a hook on every slash tx to create an IBC packet to Osmosis.
  - [ ] Need to figure out how general data communication is supposed to work over IBC
  - [ ] Need to figure out how to communicate Chain A's interfluid version. (As we have to be backwards compatible with old interfluid versions)
  - [ ] Communicate delegation amounts changing
  - [ ] Send delegation rewards over IBC at some regular cadence. (Perhaps having epochs module integrated in `x/interfluid_staking`)
  - [ ] Cross-chain governance voting
- [ ] Elongate an existing lockup
- [ ] Token-minting safety checks for `x/interfluid_staking` (As we are intending to repeat the design of superfluid_staking)
- [ ] Adapting bank supply and token supply queries accordingly

**Comment by ValarDragon** [comment]
Going to close this, mesh security changes the architecture we'd use for interfluid staking
