### ISSUE TITLE
[SA] Spend Limit - Include fee deduction to the spend limit

### ISSUE THREAD

**Issue by iboss-ptk** [osmosis-labs/osmosis#7913]
## Problem

* deduct fee happens before smart account’s ante handler
* spend limit tracks current balance in smart account’s ante handler comparing to after execution in post
* which means, fee deduction happens before track, essentially becoming untracked spend
* the risk is, since 1-click-trading = `all_of(spend_limit, sig_ver(hot_key), msg_filter(swap))` if `hot_key` is compromised, the adversary can drain ones bag ignoring spend limit by submitting failed tx.

## Tasks

- [X] move fee deductions to after authentication in the ante list
- [X] pass fees as part of the authentication request [CHAIN-406](https://linear.app/osmosis/issue/CHAIN-406/%5Bsa%5D-pass-fee-to-authenticator)
- [X] in the contract’s track: “if I’m the fee payer, track expected spend for this tx”
- [X] in confirm execution: “delete the tracked fee”

Fees used through this authenticator should accumulate on the contract if txs fail (not deleted on confirm)

- [X] on future authenticates, add any accumulated fees to the limit and see if it is exceeded
- [ ] add integration test
