### ISSUE TITLE
[SA] Spend Limit - prep-instantiate - Interactively selecting best routes

### ISSUE THREAD

**Issue by iboss-ptk** [osmosis-labs/osmosis#7924]
for routes, it show each pool information so that we can manually generate instantiate msg / update msg

It should also gives a way to

* save the selection work if not yet done for all (auto save each selection?)
* continue from saved file
* go back and change old selection
* get info about each route from saved for reviews & twap testing it

## flow

`gen-msg`

\-> for each assset
   -> select route
   -> verify twap
     -> if failed: abort and report failed pool & err msg

\-> save partial result to file

## new flag

either of these flags are mandatory

`prep-instantiate gem-msg --write-to `

`prep-instantiate gen-msg --continue-from `

## Tasks

- [X] write to
- [X] save on confirm
- [X] progress counter
- [X] continue from
- [X] progress bar
- [X] edit mode
- [X] detect excessive denom diff from config and prompt
  - [X] if state has denoms that are not in config, prompt user to confirm removing those, else they need to fix config
- [X] resulted price
- [X] update doc
- [X] rename to `sl-util`
- [X] gen default conf
- [X] expose config
