### ISSUE TITLE
Superfluid tracking issue

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#798]
Remaining items for Superfluid staking

Testing / docs strategy
- [x] #809
  - [ ] Written description of what we think we're testing via unit tests, and via particular testnet transcripts
  - [ ] What is the simulator doing right now
  - [ ] What are things we want to be testing
  - [ ] How are we testing various queries
- [ ] Internal code auditing
- [ ] Transcript of tests to run on testnet
- [ ] Simulation strategy
  - [ ] Get the simulator to setup more state (In progress)
  - [ ] Pick Invariants to test
- [ ] Document the decision wrt TWAP
- [x] Make a new function for getting the TWAP calculation with clearer documentation
- [x] Fix off by one error in endedEpoch in hooks

Code that needs to be written
- [x]  Revisit whether one lock is 100% superfluidly staked, and then how this interacts with AddTokensToLock
  - [ ] At the moment appears that you can't do 10 LP shares of pool X superfluidly staked, 5 not (at same duration)
  - [ ] The decision made in PR #836 was to make it so that SyntheticLockups lock a subset of the underlying lock's tokens. So we just need to test that we can indeed use this to not have 100% of a locks tokens superfluidly staked.
- [x] #818
  - [ ] Bank dependency on superfluid
  - [ ] Sunny idea: architect as giving bank a list of module accounts to not include
- [ ] Spend time thinking about queries to enable front-end for superfluid
- [x] Epoch bug decision (#830 )
- [ ] Fix remaining synthetic lockup bugs

Superfluid V2
- [ ] (v2 item) Governance votes for superfluid 
- [x] #819 
- [ ] (optional) Is get the work for validator set preferences
